=== smurav/db36/KiBmephi.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="nametype">
  <xs:restriction base="xs:string">
    <xs:pattern value="([a-zA-Z0-9 ])*"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="studenttype">
  <xs:restriction base="xs:string">
    <xs:pattern value="([a-zA-Z])*"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="numbertype">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1"/>
    <xs:maxInclusive value="40"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="universitytype">
  <xs:sequence>
    <xs:element name="faculty" type="facultytype"/>
  </xs:sequence>
  <xs:attribute name="name" type="nametype" use="required"/>
  <xs:attribute name="country" type="nametype" use="required"/>
  <xs:attribute name="city" type="nametype" use="required"/>
  <xs:attribute name="metro" type="nametype" use="required"/>
</xs:complexType>

<xs:complexType name="facultytype">
  <xs:sequence>
    <xs:element name="department" type="departmenttype"/>
  </xs:sequence>
  <xs:attribute name="name" type="nametype" use="required"/>
  <xs:attribute name="dean" type="nametype" use="required"/>
</xs:complexType>

<xs:complexType name="departmenttype">
  <xs:sequence>
    <xs:element name="group" type="grouptype"/>
  </xs:sequence>
  <xs:attribute name="name" type="nametype" use="required"/>
  <xs:attribute name="number" type="numbertype" use="required"/>
</xs:complexType>

<xs:complexType name="grouptype">
  <xs:sequence>
    <xs:element name="student" type="studenttype"
    maxOccurs="13" minOccurs="1"/>
  </xs:sequence>
  <xs:attribute name="name" type="nametype" use="required"/>
  <xs:attribute name="amount" type="numbertype" use="required"/>
</xs:complexType>

<xs:element name="university" type="universitytype"/>
<xs:element name="университет" substitutionGroup="university"/>
</xs:schema>

=== smurav/db36/KiBmephi.xml
<?xml version="1.0" encoding="UTF-8" ?>
<university name="Mephi" country= "Russia" city="Moscow" metro="Kashirskaya"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.w3schools.com KiBmephi.xsd">
>
	<faculty name="KIB" dean="Evseev">
		<department name="Information systems and technologies" number="36">
			<group name="K5-361" amount="13">
				<student>Anisimova</student>
				<student>Artemyev</student>
				<student>Bubenko</student>
				<student>Dzhelouhova</student>
				<student>Zamanov</student>
				<student>Miheev</student>
				<student>Pivovarov</student>
				<student>Samsonov</student>
				<student>Sidorova</student>
				<student>Solovyeva</student>
				<student>Tarmazakov</student>
				<student>Titorenko</student>
				<student>Shtanko</student>
			</group>
		</department>	
	</faculty>
</university>
