=== smurav/db36/labs/xsd/mephi.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="names">
 <xs:restriction base="xs:string">
  <xs:enumeration value="K"/>
  <xs:enumeration value="A"/>
  <xs:enumeration value="F"/>
  <xs:enumeration value="T"/>
  <xs:enumeration value="U"/>
 </xs:restriction>
</xs:simpleType> 

<xs:simpleType name="numbers">
 <xs:restriction base="xs:integer">
  <xs:minExclusive value="0"/>
  <xs:maxExclusive value="40"/>
 </xs:restriction>
</xs:simpleType>

<xs:simpleType name="nums">
 <xs:restriction base="xs:integer">
  <xs:minInclusive value="1"/>
  <xs:maxInclusive value="4"/>
 </xs:restriction>
</xs:simpleType>

<xs:simpleType name="years">
 <xs:restriction base="xs:integer">
  <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
 </xs:restriction>
</xs:simpleType>

<xs:simpleType name="students">
 <xs:restriction base="xs:string">
  <xs:pattern value="([а-яА-Я ])*"/>
 </xs:restriction>
</xs:simpleType>

<xs:complexType name="groups">
 <xs:sequence>
  <xs:element name="student" type="students" maxOccurs="40" minOccurs="1"/> 
 </xs:sequence>
 <xs:attribute name="num" type="nums" use="required"/>
 <xs:attribute name="year" type="years" use="required"/>
</xs:complexType>

<xs:complexType name="kafedras">
 <xs:sequence>
  <xs:element name="group" type="groups" maxOccurs="4" minOccurs="1"/>
 </xs:sequence>
 <xs:attribute name="number" type="xs:integer" use="required"/>
</xs:complexType>

<xs:complexType name="faculties">
 <xs:sequence>
  <xs:element name="kafedra" type="kafedras" maxOccurs="100" minOccurs="1"/>
 </xs:sequence>
 <xs:attribute name="name" type="names" use="required"/>
</xs:complexType>

<xs:complexType name="universities">
 <xs:sequence>
  <xs:element name="faculty" type="faculties" maxOccurs="5" minOccurs="1"/>
 </xs:sequence>
</xs:complexType>

<xs:element name="mephi" type="universities"/>

</xs:schema>

=== smurav/db36/labs/xsd/mephixsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mephi SYSTEM "mephi.dtd">
<mephi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="/home/student/db36/all_labs/xsd/mephi.xsd">

  <faculty name="K">
    <kafedra number="36">
      <group num="1" year="2012">
        <student>Артемьев Дмитрий</student>
        <student>Анисимова Наталья</student>
        <student>Бубенко Кирилл</student>
        <student>Джелоухова Алена</student>
        <student>Заманов Айнур</student>
        <student>Михеев Денис</student>
        <student>Пивоваров Александр</student>
        <student>Самсонов Артем</student>
        <student>Соловьева Аня</student>
        <student>Суханова Любовь</student>
        <student>Тармазаков Евгений</student>
        <student>Титоренко Алексей</student>
        <student>Штанько Александр</student>
      </group>
      <group num="2" year="2012">
        <student>Ахметсафин Владислав</student>
        <student>Галкин Александр</student>
        <student>Головко Ирина</student>
        <student>Джумайло Евгений</student>
        <student>Ерохин Владимир</student>
        <student>Каталкина Виктория</student>
        <student>Левин Андрей</student>
        <student>Молочков Ярослав</student>
        <student>Моряшова Виктория</student>
        <student>Полстянкин Константин</student>
        <student>Пурик Яна</student>
        <student>Разживин Никита</student>
        <student>Редюк Сергей</student>
        <student>Рябов Петр</student>
        <student>Скок Дарья</student>
        <student>Стрекалов Олег</student>
        <student>Чухненко Александра</student>
      </group>
    </kafedra>
  </faculty>
 <faculty name='A'>
 </faculty>
 <faculty name='T'>
 </faculty>
 <faculty name='F'>
 </faculty>
 <faculty name='U'>
 </faculty>
</mephi>  
</mephi>
